### ISSUE TITLE
It is not working on input  type="submit" 

### ISSUE THREAD

**Issue by hareom284** [LingMyat/MssJsValidationPackage#4]
Thank for make this package.

I discovered a bug in my code when I initially used the following HTML markup:

```
<button type="submit">Submit</button>
```
At that time, everything was functioning as expected. However, when I made a change to the HTML like this:

```
<input type="submit" value="submit">

```

The functionality stopped working. I would appreciate your suggestions if there might be a misconfiguration causing this issue.

**Comment by LingMyat** [comment]
Problem Solved, Thank for your testing.
